version: '3'

services:
  twitch-drops-miner:
    container_name: twitch-drops-miner
    image: 9ikj/twitch-drops-miner:latest
    volumes:
      - ./config:/TwitchDropsMiner/config
    ports:
      # - 5900:5900 #VNC_LISTENING_PORT
      - 5800:5800 #WEB_LISTENING_PORT
    environment:
      - USER_ID=0 #linux use 'id -u',see:https://github.com/jlesage/docker-baseimage-gui?tab=readme-ov-file#usergroup-ids
      - GROUP_ID=0 #linux use 'id -g'
      - VNC_PASSWORD=yourvncpassword
