version: '3'

services:
  twitch-drops-miner:
    container_name: twitch-drops-miner
    image: 9ikj/twitch-drops-miner:debain
    volumes:
      - ./config:/TwitchDropsMiner/config
    ports:
      - 5900:5900 #VNC_LISTENING_PORT
      # - 5800:5800 #WEB_LISTENING_PORT
    environment:
      - VNC_PASSWORD=yourvncpassword