name: Dockerimage Main

on:
  workflow_dispatch: 
  push:
    branches:
      - debain
    paths:
      - ".github/workflows/dockerimage-main.yml"
      - "Dockerfile"
      - "startapp.sh"
  schedule:
    - cron: '0 0 * * *'

jobs:
  twitch-drops-miner:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'debain'
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --pull --no-cache --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --tag 9ikj/twitch-drops-miner:debain

        docker push 9ikj/twitch-drops-miner:debain
